### PR TITLE
Add in-game way to Toggle DeathLink.

### PR DESCRIPTION
**Pull request by CaitSith2**
Wanted a means to be able to turn deathlink on or off mid-game, for instance, I wanted it on, but forgot to put it in the yaml.

### CODE REVIEW

**Comment by JarnoWesthof** [comment]
I dont really want to give users this ability. deathlink its a crazy rabbit hole. no cheating yourself out of it
but if people really want this :/ then we can do this but it should work using the ingame setting menu

**Comment by CaitSith2** [comment]
Okay, switched fully to the ingame setting menu.

**Comment by JarnoWesthof** [comment]
So i took a look at it today, seems like a great improvement overall

I however do not like how  deathLinkService is not static on GamePlayScreen, in the past static members causes a lot problem as state was preserved across game/save loads,
I also dont like how this `if (Settings.DeathLinkSetting.Value != (deathLinkService?.deathLinkEnabled ?? false))` is checked every frame update. 

so i think the deathlink service instead need to get an instance of the current gamesettings SettingsCollection to check if the value is on off and i dont think we should both the gameplay screen with this responseability

**Comment by JarnoWesthof** [comment]
Looking good, ill look into it a bit more when i have the code on my pc

**Pull request merged**
